In [40]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def generate_random_vector(N_processors: float, M_tasks: int, T_min: int, T_max: int) -> np.array:
    task_vector = np.random.randint(T_min, T_max, (1, M_tasks))
    return task_vector

def get_user_input(N_processors=None, M_tasks=None):
    N_processors, M_tasks = [int(i) for i in input("Введите число устройств и количество работ через пробел: ").split(" ")]
    T_min, T_max = [int(i) for i in input ("Введите через пробел минимальное и максимальное значения для автогенерации: ").split(" ")]
    vector_tasks = generate_random_vector(N_processors, M_tasks, T_min, T_max)
    matrix = np.zeros((N_processors, M_tasks))
    return (matrix, vector_tasks)

def initial_distribution(matrix, vector_tasks):
    matrix = np.zeros(matrix.shape)
    for i in vector_tasks[0]:
        indices = np.random.randint(0, matrix.shape[0])
        print(indices, i)
        if(len(matrix[indices] < matrix.shape[1])):
            matrix[indices][] = i
    return matrix

def plot_matrix(vector, title=None, ax=None):
    if ax is None:
        fig, ax = plt.subplots()
    sns.heatmap(vector, xticklabels=False, yticklabels=False, annot=True, fmt=".2f", cmap='YlGnBu', cbar=False, linewidths=2, ax=ax)
    ax.set_title(title)
    

In [18]:
matrix, vector_tasks = get_user_input()

In [48]:
print(matrix, vector_tasks)
matrix.shape[0]
print(matrix)
print(np.nonzero(matrix[0]))
#inited_matrix = initial_distribution(matrix, vector_tasks)
#plot_matrix(inited_matrix)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [17. 17.  7.  2.  6.  9.  1.]
 [17. 17.  7.  2.  6.  9.  1.]] [[17 17  7  2  6  9  1]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [17. 17.  7.  2.  6.  9.  1.]
 [17. 17.  7.  2.  6.  9.  1.]]
(array([], dtype=int64),)
